import type { MessageKey } from './fr.js';

export const en: Record<MessageKey, string> = {
  'app.name': 'KYA SolDesign', 'app.search': 'Search an action', 'app.newProject': 'New study', 'app.darkMode': 'Dark mode', 'app.lightMode': 'Light mode', 'app.sessionOnly': 'In-memory session', 'app.loading': 'Opening the application…',
  'nav.home': 'Home', 'nav.projects': 'Projects', 'nav.catalog': 'Catalog', 'nav.settings': 'Settings',
  'home.title': 'Welcome', 'home.lede': 'Start a photovoltaic study and keep a clear view of what is available.', 'home.systems': 'System types', 'home.recent': 'Recent projects', 'home.emptyProjects': 'No study in this session.', 'home.emptyProjectsHelp': 'Create an AIO study to open the technical workflow.',
  'system.aio': 'Off-grid · all-in-one inverter', 'system.aio.description': 'A single device handles the photovoltaic array, storage, and AC output.', 'system.controller': 'Off-grid · inverter and controller', 'system.grid': 'Grid-connected', 'system.diesel': 'PV and diesel hybrid', 'system.light': 'Solar street light', 'system.pump': 'Direct-coupled solar pumping', 'system.comingSoon': 'Available in a future phase',
  'action.open': 'Open', 'action.create': 'Create study', 'action.cancel': 'Cancel', 'action.confirm': 'Confirm', 'action.close': 'Close', 'action.back': 'Back', 'action.remove': 'Remove', 'action.retry': 'Retry', 'action.select': 'Select',
  'projects.title': 'Projects', 'projects.search': 'Filter by name', 'projects.empty': 'No project in the current session.', 'projects.removeSuccess': 'Study removed from the session.', 'projects.untitled': 'Untitled study',
  'catalog.title': 'Equipment catalog', 'catalog.search': 'Search manufacturer or model', 'catalog.allKinds': 'All types', 'catalog.empty': 'No equipment matches this filter.', 'catalog.error': 'The canonical catalog is unavailable.', 'catalog.provenance': 'Verified source', 'catalog.kind.pv-module': 'Photovoltaic module', 'catalog.kind.battery': 'Battery', 'catalog.kind.inverter': 'Inverter',
  'settings.title': 'Settings', 'settings.language': 'Language', 'settings.theme': 'Appearance', 'settings.desktopLater': 'Local persistence and offline operation will be added with DESK-001.', 'settings.light': 'Light', 'settings.dark': 'Dark',
  'workshop.file': 'Project file', 'workshop.backToProjects': 'Back to projects', 'workshop.notFound': 'This study does not exist in the current session.', 'workshop.project': 'Project identification', 'workshop.site': 'Site selection', 'workshop.needs': 'Consumption assessment', 'workshop.presizing': 'Pre-sizing', 'workshop.equipment': 'Equipment sizing', 'workshop.protections': 'Protection devices and wiring', 'workshop.finance': 'Financial assessment', 'workshop.dossier': 'System diagram and reports', 'workshop.title': 'Off-grid study',
  'workshop.projectName': 'Study name', 'workshop.location': 'Locality', 'workshop.weather': 'Weather reference', 'workshop.selectLocality': 'Select a canonical locality', 'workshop.selectWeather': 'Select a weather source', 'workshop.noWeather': 'No canonical weather source is available for this locality.', 'workshop.siteSaved': 'The site and its source were saved to the draft.',
  'workshop.loadName': 'Use or equipment', 'workshop.power': 'Nominal power (W)', 'workshop.quantity': 'Quantity', 'workshop.powerFactor': 'Power factor (optional)', 'workshop.simultaneity': 'Simultaneity ratio', 'workshop.hours': 'Operating hours', 'workshop.hoursHelp': 'Explicitly select each active hour.', 'workshop.loadSaved': 'The validated load was saved without running a calculation.',
  'workshop.catalogPreview': 'Canonical catalog available', 'workshop.catalogPreviewHelp': 'Review sourced references. No compatibility or quantity is recommended.', 'workshop.save': 'Save information', 'workshop.inputsOnly': 'These are draft inputs. They do not trigger any calculation.', 'workshop.catalogBrowse': 'Browse canonical catalog', 'workshop.unavailableDetail': 'No technical, financial, or dossier result is invented in this version.',
  'workshop.synoptic': 'System diagram', 'workshop.verification': 'Verification', 'workshop.documents': 'Documents', 'workshop.next': 'Next step', 'workshop.previous': 'Previous step',
  'route.notFound': 'Page not found', 'route.notFoundBody': 'This address does not match any page in this version.', 'route.segmentNotFound': 'This workshop step does not exist.', 'error.retryHelp': 'Retry reading the canonical source.', 'validation.invalid': 'Check this value.',
  'state.unavailable': 'This capability is not available yet.', 'state.owner': 'Planned in', 'state.empty': 'No data to display.', 'state.error': 'An error prevents this information from being displayed.', 'state.loading': 'Loading in progress.', 'state.stale': 'The previous result no longer matches the current inputs.',
  'palette.title': 'Search an action', 'palette.hint': 'Type to filter destinations.', 'dialog.removeProject': 'Remove this study?', 'dialog.removeProjectBody': 'This action removes the study from the current session.',
};
