export const fr = {
  'app.name': 'KYA SolDesign', 'app.search': 'Rechercher une action', 'app.newProject': 'Nouvelle étude', 'app.darkMode': 'Mode sombre', 'app.lightMode': 'Mode clair', 'app.sessionOnly': 'Session en mémoire', 'app.loading': 'Ouverture de l’application…',
  'nav.home': 'Accueil', 'nav.projects': 'Projets', 'nav.catalog': 'Catalogue', 'nav.settings': 'Réglages',
  'home.title': 'Bienvenue', 'home.lede': 'Démarrez une étude photovoltaïque et conservez une lecture claire de ce qui est disponible.', 'home.systems': 'Types de système', 'home.recent': 'Projets récents', 'home.emptyProjects': 'Aucune étude dans cette session.', 'home.emptyProjectsHelp': 'Créez une étude AIO pour ouvrir le parcours technique.',
  'system.aio': 'Autonome · onduleur tout-en-un', 'system.aio.description': 'Un appareil unique gère le champ photovoltaïque, le stockage et la sortie alternative.', 'system.controller': 'Autonome · onduleur et régulateur', 'system.grid': 'Couplé au réseau', 'system.diesel': 'Hybride PV et groupe électrogène', 'system.light': 'Lampadaire solaire', 'system.pump': 'Pompage au fil du soleil', 'system.comingSoon': 'Disponible dans une prochaine phase',
  'action.open': 'Ouvrir', 'action.create': 'Créer l’étude', 'action.cancel': 'Annuler', 'action.confirm': 'Confirmer', 'action.close': 'Fermer', 'action.back': 'Retour', 'action.remove': 'Supprimer', 'action.retry': 'Réessayer', 'action.select': 'Sélectionner',
  'projects.title': 'Projets', 'projects.search': 'Filtrer par nom', 'projects.empty': 'Aucun projet dans la session courante.', 'projects.removeSuccess': 'Étude retirée de la session.', 'projects.untitled': 'Étude sans titre',
  'catalog.title': 'Catalogue matériel', 'catalog.search': 'Rechercher un fabricant ou un modèle', 'catalog.allKinds': 'Tous les types', 'catalog.empty': 'Aucun équipement ne correspond au filtre.', 'catalog.error': 'Le catalogue canonique est indisponible.', 'catalog.provenance': 'Source vérifiée', 'catalog.kind.pv-module': 'Module photovoltaïque', 'catalog.kind.battery': 'Batterie', 'catalog.kind.inverter': 'Onduleur',
  'settings.title': 'Réglages', 'settings.language': 'Langue', 'settings.theme': 'Apparence', 'settings.desktopLater': 'La persistance locale et le fonctionnement hors ligne seront ajoutés avec DESK-001.', 'settings.light': 'Clair', 'settings.dark': 'Sombre',
  'workshop.file': 'Dossier', 'workshop.backToProjects': 'Retour aux projets', 'workshop.notFound': 'Cette étude n’existe pas dans la session courante.', 'workshop.project': 'Identification du projet', 'workshop.site': 'Choix du site', 'workshop.needs': 'Bilan des consommations', 'workshop.presizing': 'Prédimensionnement', 'workshop.equipment': 'Dimensionnement', 'workshop.protections': 'Protections et câblerie', 'workshop.finance': 'Évaluation financière', 'workshop.dossier': 'Vue synoptique et rapports', 'workshop.title': 'Étude autonome',
  'workshop.projectName': 'Nom de l’étude', 'workshop.location': 'Localité', 'workshop.weather': 'Référence météorologique', 'workshop.selectLocality': 'Sélectionnez une localité canonique', 'workshop.selectWeather': 'Sélectionnez une source météo', 'workshop.noWeather': 'Aucune source météo canonique pour cette localité.', 'workshop.siteSaved': 'Le site et sa source ont été enregistrés dans le brouillon.',
  'workshop.loadName': 'Usage ou équipement', 'workshop.power': 'Puissance nominale (W)', 'workshop.quantity': 'Quantité', 'workshop.powerFactor': 'Facteur de puissance (optionnel)', 'workshop.simultaneity': 'Coefficient de simultanéité', 'workshop.hours': 'Heures de fonctionnement', 'workshop.hoursHelp': 'Sélectionnez explicitement chaque heure active.', 'workshop.loadSaved': 'La charge validée a été enregistrée sans calcul.',
  'workshop.catalogPreview': 'Catalogue canonique disponible', 'workshop.catalogPreviewHelp': 'Consultez les références sources. Aucune compatibilité ni quantité n’est recommandée.', 'workshop.save': 'Enregistrer les informations', 'workshop.inputsOnly': 'Ces informations sont des entrées de brouillon. Elles ne déclenchent aucun calcul.', 'workshop.catalogBrowse': 'Parcourir le catalogue canonique', 'workshop.unavailableDetail': 'Aucun résultat technique, financier ou dossier n’est inventé dans cette version.',
  'workshop.synoptic': 'Synoptique', 'workshop.verification': 'Vérification', 'workshop.documents': 'Documents', 'workshop.next': 'Étape suivante', 'workshop.previous': 'Étape précédente',
  'route.notFound': 'Page introuvable', 'route.notFoundBody': 'Cette adresse ne correspond à aucune page de cette version.', 'route.segmentNotFound': 'Cette étape d’atelier n’existe pas.', 'error.retryHelp': 'Réessayez la lecture de la source canonique.', 'validation.invalid': 'Vérifiez cette valeur.',
  'state.unavailable': 'Cette capacité n’est pas encore disponible.', 'state.owner': 'Prévu dans', 'state.empty': 'Aucune donnée à afficher.', 'state.error': 'Une erreur empêche l’affichage de cette information.', 'state.loading': 'Chargement en cours.', 'state.stale': 'Le résultat précédent ne correspond plus aux entrées actuelles.',
  'palette.title': 'Rechercher une action', 'palette.hint': 'Tapez pour filtrer les destinations.', 'dialog.removeProject': 'Supprimer cette étude ?', 'dialog.removeProjectBody': 'Cette action retire l’étude de la session en cours.',
} as const;

export type MessageKey = keyof typeof fr;
