import type { ValidatedCopyKey } from './validated-fr.js';

export const validatedEn: Record<ValidatedCopyKey, string> = {
  navigation: 'Navigation', enter: 'Enter', escape: 'Escape', interface: 'Interface',
  reference: 'Reference', manufacturer: 'Manufacturer', power: 'Power', surface: 'Area', technology: 'Technology', capacity: 'Capacity', voltage: 'Voltage', efficiency: 'Efficiency', type: 'Type', pvMax: 'PV max',
  project: 'Project', projectNumber: 'Project number', projectLocation: 'Project location', client: 'Client', clientName: 'Client name', contact: 'Contact', email: 'Email',
  localityWeather: 'Locality and weather source', source: 'Source', arrayOrientation: 'Array orientation', tilt: 'Tilt', azimuth: 'Azimuth', coordinates: 'Coordinates',
  classicLoads: 'Standard appliances', name: 'Name', quantityShort: 'Qty', unitPower: 'Unit power', yieldShort: 'Eff.', hours: 'Hours', totalPower: 'Total power', realPower: 'Real power', energy: 'Energy', addRow: '+ Add a row', hourlyProfile: 'Row hourly profile', inductiveLoads: 'Inductive appliances', startingCoefficientHelp: 'starting coefficient applied to peak demand', startingCoefficient: 'Start coeff.', peak: 'Peak', noRow: 'No row', newRow: 'new row', calculatedColumns: 'grey columns are calculated',
  studyCriteria: 'Study criteria', maxLpsp: 'Maximum LPSP', maxLolp: 'Maximum LOLP', gridTariff: 'Reference grid tariff', runPresizing: 'Run pre-sizing', noFormula: 'No production formula is available—results remain empty.', waiting: 'waiting', minimumSystem: 'Minimum system to install', reliabilityEconomy: 'Reliability & economics', pvPeak: 'PV array peak power', inverterMinimum: 'Minimum inverter power', storageMinimum: 'Minimum stored energy', annualProduction: 'Annual production', producedKwhCost: 'Produced energy cost',
  pendingCalculations: 'calculations pending', quantity: 'Metric', minimum: 'Minimum', selected: 'Selected', difference: 'Difference', change: 'Change…', compatibilityLater: 'Compatibility will be calculated by EQP-001.', pvModule: 'PV module', battery: 'Battery', aioInverter: 'AIO inverter', presizedSelected: 'Pre-sized / selected comparison', pvPower: 'PV power', storage: 'Storage', inverterPower: 'Inverter power',
  protections: 'Protections', segment: 'Segment', requiredCurrent: 'Required current', selectedRating: 'Selected rating', state: 'State', cables: 'Cables', cableHelp: 'the standardized section will follow from validated protections', length: 'Length', material: 'Material', installation: 'Installation', current: 'Current', drop: 'Drop', minSection: 'Min. section', standardized: 'Standardized', copper: 'Copper', aluminium: 'Aluminium', aerial: 'Aerial', buried: 'Buried', advisedRating: 'standardized rating, advised but editable', pvToInverter: 'PV → Inverter', inverterToBattery: 'Inverter → Battery', inverterToLoads: 'Inverter → Loads',
  commercialSettings: 'Commercial settings', currency: 'Currency', vat: 'VAT', targetMargin: 'Target margin', commercialSummary: 'Commercial summary', materialCost: 'Equipment cost', installationCost: 'Installation', salePriceExclTax: 'Sale price excl. tax', salePriceInclTax: 'Sale price incl. tax', margin: 'Margin',
  dossierCompleteness: 'File completeness', toComplete: 'to complete', dossierBlocked: 'File cannot be generated', dossierBlockedHelp: 'Calculations and validations from previous steps are required.', synopticView: 'System diagram', synopticHelp: 'The production diagram will be built only from validated technical results.', document: 'Document', action: 'Action', unavailable: 'unavailable', generate: 'Generate', technicalSummary: 'Technical summary', sizingReport: 'Sizing report', singleLine: 'Single-line diagram', financialOffer: 'Financial offer',
  viability: 'Viability', dailyProfile: 'Daily profile', hoursMetric: 'Hours', sun: 'Solar resource', hourlyReliability: 'Hourly reliability', compatibility: 'Compatibility', finance: 'Finance',
};
