export const validatedFr = {
  navigation: 'Navigation', enter: 'Entrée', escape: 'Échap', interface: 'Interface',
  reference: 'Référence', manufacturer: 'Fabricant', power: 'Puissance', surface: 'Surface', technology: 'Technologie', capacity: 'Capacité', voltage: 'Tension', efficiency: 'Rendement', type: 'Type', pvMax: 'PV max',
  project: 'Projet', projectNumber: 'Numéro du projet', projectLocation: 'Localisation du projet', client: 'Client', clientName: 'Nom du client', contact: 'Contact', email: 'Courriel',
  localityWeather: 'Localité et source météo', source: 'Source', arrayOrientation: 'Orientation du champ', tilt: 'Inclinaison', azimuth: 'Azimut', coordinates: 'Coordonnées',
  classicLoads: 'Appareils classiques', name: 'Nom', quantityShort: 'Qté', unitPower: 'P. unit.', yieldShort: 'Rend.', hours: 'Heures', totalPower: 'P. totale', realPower: 'P. réelle', energy: 'Énergie', addRow: '+ Ajouter une ligne', hourlyProfile: 'Profil horaire de la ligne', inductiveLoads: 'Appareils inductifs', startingCoefficientHelp: 'coefficient de démarrage appliqué à la pointe', startingCoefficient: 'Coef. dém.', peak: 'Pointe', noRow: 'Aucune ligne', newRow: 'nouvelle ligne', calculatedColumns: 'colonnes grisées = calculées',
  studyCriteria: 'Critères de l’étude', maxLpsp: 'LPSP maximale', maxLolp: 'LOLP maximale', gridTariff: 'Tarif réseau de référence', runPresizing: 'Lancer le prédimensionnement', noFormula: 'Aucune formule de production n’est disponible — les résultats restent vides.', waiting: 'en attente', minimumSystem: 'Système minimal à installer', reliabilityEconomy: 'Fiabilité & économie', pvPeak: 'Puissance crête du champ PV', inverterMinimum: 'Puissance onduleur minimale', storageMinimum: 'Énergie stockée minimale', annualProduction: 'Production annuelle', producedKwhCost: 'Coût du kWh produit',
  pendingCalculations: 'calculs en attente', quantity: 'Grandeur', minimum: 'Minimum', selected: 'Retenu', difference: 'Écart', change: 'Changer…', compatibilityLater: 'La compatibilité sera calculée par EQP-001.', pvModule: 'Module PV', battery: 'Batterie', aioInverter: 'Onduleur AIO', presizedSelected: 'Comparatif prédimensionné / retenu', pvPower: 'Puissance PV', storage: 'Stockage', inverterPower: 'Puissance onduleur',
  protections: 'Protections', segment: 'Segment', requiredCurrent: 'Courant requis', selectedRating: 'Calibre retenu', state: 'État', cables: 'Câbles', cableHelp: 'la section normalisée découlera des protections validées', length: 'Longueur', material: 'Matériau', installation: 'Pose', current: 'Courant', drop: 'Chute', minSection: 'Section min.', standardized: 'Normalisée', copper: 'Cuivre', aluminium: 'Aluminium', aerial: 'Aérien', buried: 'Enterré', advisedRating: 'calibre normalisé, conseillé mais modifiable', pvToInverter: 'PV → Onduleur', inverterToBattery: 'Onduleur → Batterie', inverterToLoads: 'Onduleur → Charges',
  commercialSettings: 'Paramètres commerciaux', currency: 'Devise', vat: 'TVA', targetMargin: 'Marge cible', commercialSummary: 'Synthèse commerciale', materialCost: 'Coût matériel', installationCost: 'Installation', salePriceExclTax: 'Prix de vente HT', salePriceInclTax: 'Prix de vente TTC', margin: 'Marge',
  dossierCompleteness: 'Complétude du dossier', toComplete: 'à compléter', dossierBlocked: 'Dossier non générable', dossierBlockedHelp: 'Les calculs et validations des étapes précédentes sont requis.', synopticView: 'Vue synoptique', synopticHelp: 'Le schéma de production sera construit uniquement depuis des résultats techniques validés.', document: 'Document', action: 'Action', unavailable: 'indisponible', generate: 'Générer', technicalSummary: 'Synthèse technique', sizingReport: 'Rapport de dimensionnement', singleLine: 'Schéma unifilaire', financialOffer: 'Offre financière',
  viability: 'Viabilité', dailyProfile: 'Profil journalier', hoursMetric: 'Heures', sun: 'Soleil', hourlyReliability: 'Fiabilité horaire', compatibility: 'Compatibilité', finance: 'Finance',
} as const;

export type ValidatedCopyKey = keyof typeof validatedFr;
