/**
 * Codes d'erreur et d'avertissement des moteurs, traduits pour l'utilisateur.
 * Un code inconnu reste lisible par le support via la clé générique.
 */
const KNOWN = new Set([
  'COLD_TEMPERATURE_MISSING', 'PRESIZING_NOT_RUN', 'PRESIZING_OUTPUT_INVALID', 'EQUIPMENT_SELECTION_INCOMPLETE', 'EQUIPMENT_CATALOG_MISSING',
  'SIZING_REQUIREMENTS_INVALID', 'SIZING_FAILED', 'PV_NO_VALID_CONFIGURATION', 'INVERTER_PARALLEL_NOT_ALLOWED', 'INVERTER_PARALLEL_LIMIT_EXCEEDED',
  'INVERTER_POWER_OVERSIZED', 'INVERTER_CHARGE_CURRENT_UNKNOWN', 'BATTERY_DOD_UNKNOWN', 'BATTERY_VOLTAGE_MARGIN', 'VOC_COEFFICIENT_SIGN_CORRECTED',
  'VOC_COEFFICIENT_DEFAULTED', 'NO_DIMENSIONABLE_CONFIG', 'LOAD_ENERGY_MISSING', 'HOURLY_DATA_INCOMPLETE', 'ASSUMPTION_OUT_OF_RANGE', 'SIZING_NOT_RUN', 'SIZING_INVALID', 'WEATHER_FILE_MISSING', 'YEN_UNAVAILABLE', 'SITE_TIMEZONE_MISSING',
]);

export function calculationErrorKey(code: string): string {
  const first = code.split(',')[0]?.trim() ?? code;
  return KNOWN.has(first) ? `calc.${first}` : 'calc.unknown';
}
