import type { Equipment } from '@ksd/catalog';
import { sizeCableSegment, sizeProtectionSegment, type ProtectionSizingResult, type ProtectionType, type SizingOutputV1 } from '@ksd/engine';
import { useProject } from './Stub';
import { useProjects } from '../../store/project';
import { StepHead } from '../../ui/Flow';
import { Prov } from '../../ui/Prov';
import { fmt } from '../../domain/format';
import { useCatalog } from '../../app/CatalogProvider';
import { useCalculationState } from '../../app/CalculationProvider';
import type { CableSegment } from '../../app/models/projectView';

const LABEL: Record<CableSegment, string> = { pv_inverter: 'PV → Onduleur', inverter_battery: 'Onduleur → Batterie', inverter_load: 'Onduleur → Charges' };
const segments: CableSegment[] = ['pv_inverter', 'inverter_battery', 'inverter_load'];
const selected = (items: readonly Equipment[], id: string | null) => items.find((item) => item.id === id);

export function SectionProtections() {
  const project = useProject(); const update = useProjects((state) => state.update); const { equipment } = useCatalog();
  const sizingState = useCalculationState<SizingOutputV1>(project.id, 'sizing', project.updatedAt); const sizing = sizingState.status === 'ready' ? sizingState.envelope.output : null;
  const module = selected(equipment, project.selection.moduleId); const battery = selected(equipment, project.selection.batteryId); const inverter = selected(equipment, project.selection.inverterId);
  const pv = module?.kind === 'pv-module' ? module : null; const bat = battery?.kind === 'battery' ? battery : null; const inv = inverter?.kind === 'inverter' ? inverter : null;
  const inverterPowerW = sizing?.inverter.obtainedPowerKw ? sizing.inverter.obtainedPowerKw * 1000 : inv?.nominalAcPowerW ?? 0; const dcVoltageV = sizing?.battery.bankVoltageV ?? bat?.nominalVoltageV ?? inv?.nominalDcVoltageV ?? 0; const pvSeries = sizing?.pv.modulesInSeries ?? 1; const pvParallel = sizing?.pv.stringsInParallel ?? 1;
  const protections = segments.map((segment): ProtectionSizingResult => { const choice = project.protections.find((item) => item.segment === segment); return sizeProtectionSegment({ segment, moduleIscA: pv?.shortCircuitCurrentA, moduleVocV: pv?.openCircuitVoltageV, pvStrings: pvParallel, pvModulesInSeries: pvSeries, inverterPowerW, dcVoltageV, acVoltageV: inv?.nominalAcVoltageV ?? 230, selectedCaliberA: choice?.caliberA, selectedType: choice?.type }); });
  const cables = project.cables.map((cable) => { const protection = protections.find((item) => item.segment === cable.segment); return sizeCableSegment({ segment: cable.segment, currentA: protection?.caliberA ?? 0, voltageV: protection?.serviceVoltageV ?? 0, lengthM: cable.length, material: cable.material, installation: cable.installation, phase: cable.segment === 'inverter_load' ? 'single_phase' : 'dc', maxDropPercent: cable.maxVoltageDropPercent }); });
  const num = (value: string) => { const parsed = Number.parseFloat(value.replace(',', '.')); return Number.isFinite(parsed) ? parsed : 0; };
  return <div className="sheet"><StepHead slug="protections" aside={<span className="label">Le type et le calibre sont des choix explicites ; les valeurs dérivées restent en lecture seule.</span>} />
    <section><div className="tbl-title"><h2 className="h-sec">Protections</h2><span className="label">choisir d’abord le type, puis un calibre compatible</span></div><div className="tbl-wrap"><table className="tbl t-prot"><thead><tr><th>Segment</th><th>Type retenu</th><th className="derived">Courant requis<span className="unit">A</span></th><th className="pick">Calibre retenu<span className="unit">A</span></th><th className="derived">Tension de service<span className="unit">V</span></th><th className="derived">Qté</th><th>État</th></tr></thead><tbody>{protections.map((protection) => <ProtectionRow key={protection.segment} protection={protection} label={LABEL[protection.segment]} onTypeChange={(type) => update((draft) => { const row = draft.protections.find((item) => item.segment === protection.segment); if (row) { row.type = type; row.caliberA = null; } })} onCaliberChange={(caliber) => update((draft) => { const row = draft.protections.find((item) => item.segment === protection.segment); if (row) row.caliberA = caliber; })} />)}</tbody></table></div><p className="label" style={{ marginTop: 6 }}>Aucun type ou calibre n’est sélectionné automatiquement. Les calibres affichés respectent les bornes de la plage admissible.</p></section>
    <section><div className="tbl-title"><h2 className="h-sec">Câbles</h2><span className="label">quatre entrées utilisateur ; le reste est calculé</span></div><div className="tbl-wrap"><table className="tbl t-cables"><thead><tr><th>Segment</th><th>Longueur<span className="unit">m</span></th><th className="pick">Matériau</th><th className="pick">Mode de pose</th><th>Chute max.<span className="unit">%</span></th><th className="derived">Courant<span className="unit">A</span></th><th className="derived">Section thermique<span className="unit">mm²</span></th><th className="derived">Normalisée<span className="unit">mm²</span></th><th className="derived">État</th></tr></thead><tbody>{project.cables.map((cable, index) => { const result = cables[index]!; return <tr key={cable.segment}><td>{LABEL[cable.segment]}</td><td><input className="cell-in" value={cable.length} aria-label={'Longueur ' + LABEL[cable.segment]} onChange={(event) => update((draft) => { draft.cables[index].length = num(event.target.value); })} /></td><td className="pick"><select className="cell-in" value={cable.material} aria-label={'Matériau ' + LABEL[cable.segment]} onChange={(event) => update((draft) => { draft.cables[index].material = event.target.value as 'copper' | 'aluminium'; })}><option value="copper">Cuivre</option><option value="aluminium">Aluminium</option></select></td><td className="pick"><select className="cell-in" value={cable.installation} aria-label={'Mode de pose ' + LABEL[cable.segment]} onChange={(event) => update((draft) => { draft.cables[index].installation = event.target.value as 'buried' | 'not_buried'; })}><option value="not_buried">Non enterré</option><option value="buried">Enterré</option></select></td><td className="pick"><select className="cell-in" value={cable.maxVoltageDropPercent} aria-label={'Chute maximale ' + LABEL[cable.segment]} onChange={(event) => update((draft) => { draft.cables[index].maxVoltageDropPercent = Number(event.target.value); })}><option value={1}>1</option><option value={2}>2</option><option value={3}>3</option></select></td><td className="derived num">{fmt(result.currentA, 1)}</td><td className="derived num">{fmt(result.thermalSection, 1)}</td><td className="derived num"><b>{result.state === 'blocked' ? '—' : fmt(result.normalizedSection, 1)}</b></td><td className="derived">{result.state === 'valid' ? 'Conforme' : result.state === 'blocked' ? 'À compléter' : 'Indisponible'}</td></tr>; })}</tbody></table></div></section></div>;
}

function ProtectionRow({ protection, label, onTypeChange, onCaliberChange }: { readonly protection: ProtectionSizingResult; readonly label: string; readonly onTypeChange: (type: ProtectionType | null) => void; readonly onCaliberChange: (caliber: number) => void }) {
  return <tr><td>{label}</td><td className="pick"><select className="cell-in" value={protection.selectedType ?? ''} aria-label={'Type de protection ' + label} onChange={(event) => onTypeChange((event.target.value || null) as ProtectionType | null)}><option value="">Choisir un type</option>{protection.allowedTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></td><td className="derived num"><Prov title="Courant à couvrir" formula={protection.segment === 'pv_inverter' ? 'I ≥ 1,5 × Np × Isc module' : 'I ≥ 1,25 × P onduleur / U'} rows={[["Courant requis", fmt(protection.requiredA, 2) + ' A'], ['Calibres compatibles', protection.options.length ? protection.options.join(' · ') : 'aucun']]} source="Protections · règles core v1">{fmt(protection.requiredA, 1)}</Prov></td><td className="pick">{protection.options.length ? <select className="cell-in" value={protection.caliberA ?? ''} aria-label={'Calibre ' + label} onChange={(event) => onCaliberChange(Number(event.target.value))}><option value="">Choisir un calibre</option>{protection.options.map((option) => <option key={option} value={option}>{fmt(option)}</option>)}</select> : protection.state === 'estimated' && protection.caliberA !== null ? <span title="Aucun calibre catalogue ne couvre ce courant ; le courant calculé est utilisé.">{fmt(protection.caliberA, 1)}</span> : '—'}</td><td className="derived num">{fmt(protection.serviceVoltageV, 1)}</td><td className="derived num">{protection.quantity}</td><td><span className={`badge ${protection.state === 'valid' ? 'ok' : protection.state === 'unavailable' ? 'bad' : 'warn'}`}>{protection.state === 'valid' ? 'Validé' : protection.state === 'awaiting-type' ? 'Type requis' : protection.state === 'awaiting-rating' ? 'Calibre requis' : protection.state === 'estimated' ? 'Calibre estimé' : 'Indisponible'}</span></td></tr>;
}
